apiVersion: 1
datasources:
  - name: TelemetryDB
    type: postgres
    access: proxy
    orgId: 1
    url: timescaledb:5432
    database: telemetry_data
    user: admin
    password: admin
    jsonData:
      sslmode: disable
      postgresVersion: 1700
      timescaledb: true
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
    secureJsonData:
      password: admin
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
